### ISSUE TITLE
MalinowskaMichalczykPrzypasniak Raport badawczy

### ISSUE THREAD

**Issue by olgaprzypasniak** [pbiecek/WarsztatyBadawcze#101]

**Comment by pbiecek** [comment]
Ponieważ tytuł raportu to 'What may impact the time of solving tasks on PISA 2015', to biorąc pod uwagę Pań raport, bardzo brakuje mi wykresu z zależnością Stres (na osi OX) vs. czas rozwiazywania zadania po normalizacji (oś OY) ew. procent rozwiązanych zadań (oś OY). Teraz poziom stresu jest zawsze kodowany kolorem. 
Czy mogą dodać jeszcze Panie taki wykres?

**Comment by olgaprzypasniak** [comment]
Dodałyśmy wykres, o którym Pan pisał

**Comment by pbiecek** [comment]
Zaliczone jako zadanie na 4,5 (na tym wykresie obok średnich można było zaznaczyć słupki błędów, skrajne grupy są pewnie mało liczne i miałyby szerokie słupki błędów).
Więcej komentarzy prześlę jak tylko otrzymam feedback od osób z zespołu PISA
