### ISSUE TITLE
Raport PPopiolekAPszczolkowska

### ISSUE THREAD

**Issue by popiolekp** [pbiecek/WarsztatyBadawcze#104]

**Comment by pbiecek** [comment]
Zaliczone jako ocena 4,5. 
Szkoda, że nie zrobiły Panie porównań ,,co by było gdyby usunąć wpływ strategii'', ten raport ciekawiej by się czytało. Proszę o informacje czy zgadzają się Panie aby przesłać do osoby z zespołu PISA, więcej komentarzy umieszczę jak już dostanę od niej feedback.

**Comment by popiolekp** [comment]
Dzień dobry,

zgadzamy sie na wysłanie naszego raportu do osób z PISA.

Paulina Popiołek

08.05.2017 12:37 AM "Przemysław Biecek" <notifications@github.com>
napisał(a):
