### ISSUE TITLE
Zadanie 0

### ISSUE THREAD

**Issue by stolarczyk** [pbiecek/WarsztatyBadawcze#24]
Zespół BrodeckaStolarczyk

**Comment by pbiecek** [comment]
Wyniki wszystkich skryptów powinny być reprodukowalne. W duchu reproducible research, co znaczy tyle, że skrypt należałoby rozpocząć od wczytywania danych z sav.
Warto też używać knitra aby dodatkowo zamieścić komentarze co jest gdzie analizowane i przy okazji umieścić kilka przykładowych wierszy wyniku.

**Comment by pbiecek** [comment]
Wyniki z kolumną z wagami
na końcu knitra przykładowa tabela
wyniki dla math+reading+scie
