### ISSUE TITLE
Zadanie na 3 BrodeckaStolarczyk

### ISSUE THREAD

**Issue by stolarczyk** [pbiecek/WarsztatyBadawcze#25]

**Comment by pbiecek** [comment]
wyniki w excelu lub innym pliku
ważone statystyki - czasy i liczba rozwiązanych zadań
wykres pokazujące różnice pomiędzy krajami ze względu na czas i jakość rozwiązanych zadań
wyniki tylko dla bookid 31-66

**Comment by pbiecek** [comment]
Wszystko dobrze, ale proszę wprowadzić jeszcze takie zmiany:

* Jeżeli kod ma być reprodukowalny, to nie może rozpoczynać się od setwd(), w samym skrypcie nie powinno być bezwzględnych ścieżek
*Jeżeli kod ma być reprodukowalny to nie można pobierać source() z internetu kodu, te zależności mogą się zmienić. Zewnętrzny kod powinien być dołączony do projektu i odpowiednio oznakowany (informacja o źródle i licencji)
* Wykresy mają tytuły i to jest dobre, ale brakuje opisów osi. Są jakieś techniczne koszmarki typu 'factor(CNT)'.
*Nazwy krajów powinny być albo pełne albo warto dodać do knitra słowniczek ISO2 - nazwa kraju opisy są zbyt skąpe. Powinna być informacja co jest robione, a tu brakuje np. infroamcji o metodzie budowania dendrogramu
* Najważniejsze wnioski powinny być na samej górze (executive summary)

**Comment by pbiecek** [comment]
Zaliczone,
mapy wyglądają dobrze,
struktura dokumentu dobra (kod na dole, wnioski u góry),
warto się jeszcze pokusić by jakoś nazwać znalezione klastry. Zamiast 1, 2, 3, 4, 5 coś łatwiejszego w interpretacji
