### ISSUE TITLE
Zadanie na 3 MazurekSmudaTopolski

### ISSUE THREAD

**Issue by smudap** [pbiecek/WarsztatyBadawcze#27]

**Comment by smudap** [comment]
Do poprawy:

1. W zadaniu 3 dać datę.
2. Wyniki wybrać 5 krajów (np. Polska, Korea + coś większego i z Europy), wybrać podzbiór zadań. Zrobić graficznie. Tabelki zapisać do Excela. Do porównania można spróbować ANOVE. Nie tylko brać zadań z jednej grupy, tzn. wziąć ANOVE dla różnych podgrup (reading, science i maths).
3. Użyć wag w średniej.

Do zadania 3.5:

1. Pokazać te zależności na wykresie, który jest związany z rozkładem. (Dla Korei będzie płaskie, bo robią szybko)
2. Wziąć np. różnicę średnich lub median.

**Comment by pbiecek** [comment]
W zadaniu 3 nie ma żadnych komentarzy, obserwacji wniosków z wyników. Należy je dodać.
Proszę też dodać spis treści (floating_toc) i numerować rozdziały/sekcje. Inaczej nie sposób odnosić się do wyników.
Ostatni wykres ma tam małe punkty, że jest mało czytelny.
Sam plik knitra powinien zaczynać się od najważniejszych wyników, później można umieszczać kody R i wyniki z tych kodów.

**Comment by pbiecek** [comment]
Zaliczone,
choć w przyszłości proszę zwrócić uwagę na:
- brak jednostek w osicie osi [min]
- opis osi 'Kraj' jest zbędny gdy na osiach są napisy 'Polska' , 'USA' , 'Finlandia'
- opis powinine być zgodny z wykresem, tutaj raz w opisie jest 55% a na wykresie 0,55
