### ISSUE TITLE
Zadanie 0 Baranowska - Jóźwik

### ISSUE THREAD

**Issue by flaminka** [pbiecek/WarsztatyBadawcze#29]
1. Próbki zbiorów w raporcie html
2. Usunąć BOOKID > 67
3. Dodać session_info() na końcu pliku
4. Poprawić czytelność kodu (dodać setwd(), usunąć ścieżki bezpośrednie do plików)

**Comment by pbiecek** [comment]
Zaliczone.
Bonus za użycie SASa i pierwsze przyjęte rozwiązanie.
kody R są dosyć brutalne, można by poszukać krótszych i bardziej eleganckich rozwiązań
W przyszłości proszę też spis treści umieszczać jako floating toc, wygląda i korzysta się z niego znaczeni lepiej.
