### ISSUE TITLE
Zadanie 3 Baranowska - Jóźwik

### ISSUE THREAD

**Issue by flaminka** [pbiecek/WarsztatyBadawcze#30]
1. Stworzyć pliki excelowe ze statystykami dla pytań
2. Dodać wagę do zbioru i liczyć statystyki uwzględniając wagę
3. Zwizualizować wyniki na wykresach (np. dla 5 wybranych krajów, dla wybranych pytań)

**Comment by pbiecek** [comment]
Zaliczone (bonus za D3)
