### ISSUE TITLE
Zadanie 3 PopiołekPszczółkowska

### ISSUE THREAD

**Issue by popiolekp** [pbiecek/WarsztatyBadawcze#45]
1. Poprawić układ sprawozdania (dodać spis treści, podzielić na części, wyeksponować najważniejsze wnioski).
2. Dobrze opisać wykresy (dane, na podstawie których zostały stworzone).
3. Dodać przykładowe wiersze wynikowej tabeli ze statystykami, na podstawie której wykonane są wykresy.
4. Zamienić jednostkę czasu na minuty (sekundy).
5. Dodać pełne nazwy krajów.

**Comment by pbiecek** [comment]
Zaliczone,
wykresy w plotly to dobry pomysł,
struktura dokumentu też jest dobra
Jeżeli chodzi o osie, to do zastanowienia się pozostawiam czy w przyszłości lepiej zamienić jednostki na minuty, czy zostawić charakterystyczne ticks na 30,60,90,120
