### ISSUE TITLE
Zadanie 3.5 BrodeckaStolarczyk

### ISSUE THREAD

**Issue by stolarczyk** [pbiecek/WarsztatyBadawcze#47]

**Comment by pbiecek** [comment]
Ponownie jest 'source' w kodzie
W wynikach potrzebne są informacje co jest przedstawione na wykresach,
rozne zachowanie na pozycjach 1,3 vs 2,4 jest ciekawe, ale trudno odgadnac czym jest kropka

**Comment by pbiecek** [comment]
To zadanie juz zaliczam, proszę się skupić na zadaniach z kolejnych etapów
