### ISSUE TITLE
Zadanie 3.5 PopiołekPszczółkowska

### ISSUE THREAD

**Issue by popiolekp** [pbiecek/WarsztatyBadawcze#51]

**Comment by pbiecek** [comment]
Brakuje opisow,
jak rozumiem to zadanie jest jeszcze w trybie do dyskusji

**Comment by pbiecek** [comment]
Zaliczone,
Dobrze przygotowane sprawozdanie.
O czym na przyszłość pamiętać:
-	spis treści może pływać, jest to dużo wygodniejsze (toc_floating)
-	W plikach Excela nazwy kolumn mogłyby być dłuższe, by łatwiej było odgadnąć co jest opisane w danej kolumnie (czym różni się stat_sex.xlsx od stat_sex_prop.xlsx)
-	W opisie znajdują się odwołania do pliku ‘stat_position.xlsx‘, ale w katalogu na Google Drive już tego pliku nie ma
-	W podsumowaniach (które są dobre) znajduje się np. ‘różnice między spadkiem czasu rozwiązywania zadań na pozycjach 1-2 oraz 3-4 nie zawsze idą w parze z niskimi średnimi czasami czego przykładem są Finlandia, Wielka Brytania oraz Kanada.’ Ale już z tego opisu nie wynika jak to wygląda w wymienionych krajach, aby się dowiedzieć trzeba przeglądać wyniki
-	Na wykresach zamiast skrótów mogłyby być pełne nazwy krajów
-	Z wykresu 4.1 trudno odczytać jaka jest pozycja Polski, a pewnie dałoby się to pokazać
-	Na wykresie ‘Różnica w średnich czasach….’’ Na osi OY nie jest ‘czas’ ale ‘różnica średnich czasów’
W całym raporcie najbardziej przeszkadza mi to że wyniki dotyczą średnich w krajach bez uwzględnienia jak wygląda zróżnicowanie wyników wewnątrz kraju.
