### ISSUE TITLE
Zadanie 4 BrodeckaStolarczyk

### ISSUE THREAD

**Issue by stolarczyk** [pbiecek/WarsztatyBadawcze#57]

**Comment by pbiecek** [comment]
Do poprawy:
- w htmlu nie powinno być ostrzerzeń, teraz wygląda to nieczytelnie
- struktura powinna być taka: wnioski (3-4 punkty), wyniki (wykresy, tabele, opis), kod R (osobno, jako osobny rozdział)
- brakuje spisu treści, sekcje powinny być numerowane
- przy wynikach jest wykres i kod, brakuje jakiegokolwiek komentarza, proszę zerknąc do innych zaliczonych raportów jak wyglądają

**Comment by pbiecek** [comment]
Zaliczone
