### ISSUE TITLE
BaranowskaJozwik zadanie 3.5

### ISSUE THREAD

**Issue by flaminka** [pbiecek/WarsztatyBadawcze#60]

**Comment by pbiecek** [comment]
Zaliczone. 
To dobry pomysł by nazywać pliki z danymi Z0.... / Z3... / Z3_5... 

Są wyniki z podziałem na płeć, które są moim zdaniem bardzo bardzo ciekawe (wygląda na to, że chłopcy rozwiązują krócej zadania, ale czy się szybciej nudzą? Ciekawie byłoby porównać płcie w obszarach, w czytaniu to dziewczynki powinny szybciej odpowiadać)
ale nie mają komentarza, jest tylko wykres.
