### ISSUE TITLE
BaranowskaJozwik 4

### ISSUE THREAD

**Issue by flaminka** [pbiecek/WarsztatyBadawcze#61]

**Comment by pbiecek** [comment]
Wygląda ciekawie, dwa komentarze:
- Byłoby świetnie, do segmentacji dodać też informację o wynikach zadań. Teraz w opisie grup są interpretacje a, b, c, ale czytając te opisy odnoszę wrażenie, że można rozdzielić 1a od 1b itp. Czy to jest jeszcze planowane.
- obecnie porównywane są tylko kraje, ale czy zmienność między szkołami w krajach jest duża? Czy sposób postępowania zależy bardziej od ucznia czy jest typowy dla szkoły (i uczniowie z jednej szkoły zachowują się podobnie)?

**Comment by flaminka** [comment]
1. 
Dla przykładu:
interpretacja:
        a) rozwiązuje wszystkie zadania powoli, by zrobić to dokładnie
        b) rozwiązuje wszystkie zadania powoli, gdyż wolno myśli
jest niemożliwa do rozdzielenia w zbiorze, bez uwzględnienia wcześniej wyników uczniów. Jeśli dobrze zrozumiałyśmy, strategie mają być wyznaczane niezależnie od wyniku, bo ciężko też powiedzieć, że ktoś zaplanował dobrze lub źle rozwiązywać zadania, a nawet jeśli to nie musiało mu się to udać. Nasza segmentacja opiera się tylko o strategie planowania rozkładu czasu poświęconego na każdy z działów, którą później zanalizujemy pod kątem wyników w zadaniu 4.5.
Podane przez nas interpretacje mają tylko zwrócić uwagę na możliwą różnorodność danego segmentu.
Zatem czy możemy uwagę 1 uwzględnić po prostu przez realizację zadania 4.5?

2.  Czy dodanie analogicznej heatmapy dla szkół w Polsce zrealizuje tą sugestię?

**Comment by pbiecek** [comment]
Ad 1, tak
Ad 2, zamiast mapy ciepła może hierarchiczna analiza wariancji? 
Z pytaniem czy ważniejszy jest efekt ucznia czy efekt szkoły (z uwagi na wielkość danych pewnie dla wybranych krajów/szkół)

**Comment by flaminka** [comment]
Do raportu dodałyśmy punkt 4:  Wizualizacje rozkładu strategii w szkołach w Polsce (przeprowadziłyśmy test za pomocą ANOVY i dodałyśmy wykres)

**Comment by pbiecek** [comment]
Zaliczone
