### ISSUE TITLE
Zadanie 0 Kalamarz Lepicka Zdon

### ISSUE THREAD

**Issue by lepickad** [pbiecek/WarsztatyBadawcze#63]

**Comment by pbiecek** [comment]
Zaliczone,
ale kod powinien być bardziej uporządkowany / ze strukturą. 
Obecny kod ma dużo powtórzeń szczególnie elementy po '#Tworzenie zbioru tabela'
Powinna to być pętla wywołująca funkcję.
Teraz skrypt trudny w analizie
