### ISSUE TITLE
Zadanie 3 Kałamarz Łępicka Zdon

### ISSUE THREAD

**Issue by lepickad** [pbiecek/WarsztatyBadawcze#65]

**Comment by pbiecek** [comment]
Zaliczone,
choć szkoda że te ostatnie wykresy (z efektem płci) są dla wyników uczniów a nie dla czasów.
Jak wyglądają wyniki to już właściwie wiadomo od pierwszych PISA, ale jak różnią się czasy tego jeszcze nie wiadomo i to jest dużo ciekawsze
