### ISSUE TITLE
zadanie 3 panimash kocinski

### ISSUE THREAD

**Issue by sashapanimash** [pbiecek/WarsztatyBadawcze#70]

**Comment by pbiecek** [comment]
Są dwa pliki, nie wiadomo który oceniać, ale oba niezgodne z raportami.Proszę obejrzeć rozwiązania innych zespołów,
brakuje tutaj i spisu treści i opisów i struktury

**Comment by pbiecek** [comment]
Zaliczone, w aplikacji shiny brakuje opisów, przez co trudno zrozumieć co dokładnie jest pokazywane
