### ISSUE TITLE
zadanie 3.5 panimash kocinski

### ISSUE THREAD

**Issue by sashapanimash** [pbiecek/WarsztatyBadawcze#71]

**Comment by pbiecek** [comment]
Raport powinien zaczynać się od:
1. spis treści
2. wnioski
3. wyniki wraz z komentarzami
4. kody R (na samym końcu w załączniku

Jeżeli coś jest tabelą to powinno być przedstawione jako tabele, teraz tableka powyżej punktu 3. jest całkowicie nieczytelna

**Comment by pbiecek** [comment]
Pomysł by analizować osobno zadania najłatwiejsze i najtrudneijsze jest bardzo dobry, tym bardziej że wychodzą ciekawe wnioski. Szkoda że przredstawione są wyniki tylko dla jednego zadania w grupie (jedno z math, scie, read), ciekawie byłoby zobaczyć kolejne skrajne zadania.
Zadanie zaliczone
