### ISSUE TITLE
BaranowskaJozwik 4.5

### ISSUE THREAD

**Issue by flaminka** [pbiecek/WarsztatyBadawcze#73]

**Comment by pbiecek** [comment]
Zaliczone, 
kilka drobiazgów na przyszłość:
- wyniki testowania najczęściej podaje się podając p-wartość a nie wartość statystyki i kwantyle.
- częściowe wyniki warto zapisywać (to i się podobało w poprzednich etapach), tutaj można dla każdego ucznia zapisać jego przypisanie do segmentu (w pliku txt)
- okazuje się, że mapy ciepła mają prawie tylu przeciwników co wykresy kołowe. Pierwszy wykres (z profilami) jest znacznie znacznie lepszy
