### ISSUE TITLE
MalinowskaMichalczykPrzypasniak - zadanie 4

### ISSUE THREAD

**Issue by olgaprzypasniak** [pbiecek/WarsztatyBadawcze#79]

**Comment by pbiecek** [comment]
Proszę o wprowadzenie następujących zmian:
- w nazwach sekcji dodać numery (1., 2., 3. )
- we wnioskach, przy każdym wniosku odwołać się do numeru sekcji z którego wynika ten wniosek 
- strategiom proszę przypisać nazwy, teraz bardzo trudno się czyta opisy gdy strategie są surowymi liczbami
