### ISSUE TITLE
Kałamarz Łępicka Zdon - zadanie 3.5

### ISSUE THREAD

**Issue by lepickad** [pbiecek/WarsztatyBadawcze#81]

**Comment by pbiecek** [comment]
Generalnie ok, ale proszę jeszcze zmienić:
- do każdej sekcji dodać numer (Podstawowe statystyki -> 1.2 Podstawowe statystyki)
- Na początku raportu umieścić informację co jest celem raportu i w których numerach sekcji które zele zostały zrealizowane

**Comment by pbiecek** [comment]
Zaliczone
