### ISSUE TITLE
Kałamarz Łępicka Zdon - zadanie 4.5

### ISSUE THREAD

**Issue by lepickad** [pbiecek/WarsztatyBadawcze#83]

**Comment by pbiecek** [comment]
Uwagi jak w poprzednim punkcie (numery sekcji, wnioski na początku)
Plus, celem tego zadania jest uwzględnienie różnic w wynikach uczniów stosujących różne strategie. W raporcie brakuje takiego porównania, tj nie ma zestawienia sprawdzającego jak strategia jest związana z wynikami uczniów (wyniki - albo ile zadań rozwiązani poprawnie, albo jaki mieli średni PV)

**Comment by pbiecek** [comment]
Zaliczone, ale widać w tym raporcie brak czasu
