### ISSUE TITLE
Kałamarz Łępicka Zdon - zadanie 4

### ISSUE THREAD

**Issue by lepickad** [pbiecek/WarsztatyBadawcze#85]

**Comment by pbiecek** [comment]
Nazwy strategii to dobry pomysł, zakres jest generalnie ok, ale:
- niektóre tabele są wąskie inne szerokie, najlepiej by wszystkie były podobne (np szerokie)
- rozdziały i sekcje proszę ponumerować, łatwiej się do niech odnosić
- na początku jest cel i to jest dobre, poniżej powinny być Wnioski z 3-4 punktami podsumowującymi najważniejsze wnioski z analiz. Mogą być te co na końcu raportu, ale proszę dodać informacje z którego punktu wynika dany wniosek
- w tabelach kolumny niewiele znaczą, jest np. kolumna 'ile' ale nie wiadomo jaka jest jednostka ani czego jest ile
- do każdej tabeli najlepiej dodać wykres (np. słupkowy)

**Comment by pbiecek** [comment]
Zaliczone
