### ISSUE TITLE
Zadanie 4.5 BrodeckaStolarczyk

### ISSUE THREAD

**Issue by stolarczyk** [pbiecek/WarsztatyBadawcze#87]

**Comment by pbiecek** [comment]
Uwagi jak w poprzednim zadaniu,  dodatkowo:
- Zamiast zdania 'Analogicznie do poprzedniego punktu, oczyszczamy wyniki z wpływu strategi i uśredniamy w grupach.' powinien być szczegółowy opis jak usunąć wpływ strategii.  Można zrobić to na wiele sposobów, trzeba opisać ten zastosowany. Sam kod R to za mało.
- Wyniki testów powinny być wzbogacone o komentarz.
- Wnioski w podsumowaniu są dobrze opisane, ale należy do każdego wniosku wskazać w którym punkcie znajdują się argumenty przemawiające za tym wnioskiem

**Comment by pbiecek** [comment]
Celem tego punktu było (cytując z www) 'Należy odpowiedzieć na pytanie, czy różnice w stosowanych strategiach mają wpływ na końcowy wynik osiągnięty w badaniu PISA. Oraz jak wyglądałby końcowy ranking PISA gdyby usunąć wpływ stosowanej strategii.'
W państwa raporcie odpowiada to punktom 3, 4 i 5. 
Z punktu 3 można dowiedzieć się że jest jakaś zależność (ANOVA) pomiędzy wynikami a strategią ale nie wiadomo jaka. Jedynie że złożona, ponieważ interakcje są istotne.
W punktach 4 i 5 usuwane są addytywne efekty strategii i kraju, ale przecież z punktu 3 wynika że istotne są interakcje. Brakuje dyskusji co zrobić z interakcjami i jak je uwzględnić. Brakuje wniosków dotyczących nowego rankingu, czy się zmienił, czy pozostał taki sam, w których krajach zmienił się najbardziej itp.
To zadanie nie jest zaliczone.

**Comment by stolarczyk** [comment]
Treść zadania brzmi:
Należy odpowiedzieć na pytanie, czy różnice w stosowanych strategiach mają wpływ na końcowy wynik osiągnięty w badaniu PISA. Oraz jak wyglądałby końcowy ranking PISA gdyby usunąć wpływ stosowanej strategii.

Wynik testu ANOVA odpowiada na pierwsze pytanie. 
Tabela na końcu raportu odpowiada na drugie pytanie. Nie pytał Pan o to, jak się zmienia ranking tylko jak wygląda nowy ranking. Myślę, że na to pytanie tabela odpowiada w pełni.

Uważam, że zadanie powinno zostać zaliczone.

**Comment by pbiecek** [comment]
(1) W punkcie 5 nie jest przedstawiony ranking, jest tabela ze średnimi które można sobie posortować, ale nie sposób z niej zorientować się co do rankingu. Najprostszy przykład, proszę powiedzieć mi na podstawie tej tabli jakie miejsce w rankingu ma Polska.
(2) Sposób usuwania efektu strategii nie uwzględnia wyników z punktu 3, czyli interakcji. Nawet więc przyjmując, że w tabeli ze średnimi można odczytać ranking, brakuje tutaj argumentacji, że wartości w tabeli są liczone poprawnie.
(3) Na każdym etapie prezentacji było podkreślane, że wynik jest tyle wart co wnioski z niego płynące. A tutaj nie ma żadnych wniosków związanych z rankingiem po usunięciu wpływu strategii. 

Jeżeli nie zgadzają się Państwo z tą argumentacją, zapraszam na konsultacje w piątek przed zajęciami. Dokładną godzinę można umówić mailowo.
