### ISSUE TITLE
Zadanie 4 MazurekSmudaTopolski

### ISSUE THREAD

**Issue by topolskib** [pbiecek/WarsztatyBadawcze#89]

**Comment by pbiecek** [comment]
W zadaniu 3.4 struktura była dobra, a tutaj wszystkie uwagi zignorowane. Numerowane sekcje, spis treści, wnioski na górze
W opisie segmentacji jest mowa o odległości euklidesowej, a wzór podany dla innej odległości, to jak jest?
Nie jest jasne co jest przedstawione w tabeli 'otrzymane grupy'
Jeżeli to analiza hierarchiczna, to te grupy są w hierarchii, powinna być pokazana
Nie mam pojęcia jak czytać ostatni wykres,
prawdopopobnie zamienione są opisy osi
Pozostało jeszcze trochę pracy

**Comment by pbiecek** [comment]
Celem zadania było zidentyfikowanie strategii uczniów a następnie porównanie krajów/szkół z uwagi na te strategie. 
W rozwiązaniu  rozdziale 'Rozkład grup wśród krajów' przedstawione są rozkłady, których składowe nie sumują się do 100% a cały komentarz dotyczący porównania krajów sprowadza się do 'Widać, że rozkłady nie różnią się zbytnio między sobą.'
Tytuły w stylu 'Rozkład wyników wśród grup' są nieczytelne, wnioski są nieczytelne, wizualizacja niekompletna i nic nie mówiąca.
Zadanie nie jest zaliczone.
