### ISSUE TITLE
Zadanie 4 BIGPYTHONS

### ISSUE THREAD

**Issue by sashapanimash** [pbiecek/WarsztatyBadawcze#91]

**Comment by pbiecek** [comment]
Proszę zmienić nazwy strategii. 
Brakuje wniosków,
nie ma wyników, wykresów, nie ma co tutaj oceniać

**Comment by pbiecek** [comment]
Na GitHubie nie ma apliakacji shiny

**Comment by sashapanimash** [comment]
Aplikacja shiny jest w zadaniu 3

**Comment by pbiecek** [comment]
Nie ma wniosków, nie ma wykresów, przypadkowe liczby w kilku tabelach. 
Zadanie nie jest zaliczone. Poprzednie (na 3,5) było znacznie znacznie lepiej przygotowane.

**Comment by sashapanimash** [comment]
Uważam, że zadanie powinno zostać zaliczone

**Comment by pbiecek** [comment]
A argumenty?
