### ISSUE TITLE
Kałamarz Łępicka Zdon - Zadanie5

### ISSUE THREAD

**Issue by lepickad** [pbiecek/WarsztatyBadawcze#96]

**Comment by pbiecek** [comment]
Ogólnie to bardzo podoba mi się i forma i treść,
w szczegółach: 
- na wykresach (słupkowych) proszę na osi OY umieścić jednostki i informacje co jest pokazywane
- na końcu można umieścić linki do poprzednich raportów (nawet jeżeli sa w języku polskim), adresy URL są długie, można je skrócić np. z użyciem bitly
- rysunki powinny mieć numery, by dało się do nich odnieść. np. Figure 1, Figure 2....
- brakuje informacji która strategia co oznacza, jeżeli ktoś czyta tylko ten raport nie będzie wiedział jakie są różnice pomiędzy strategiami
- Zamiast II Strategy, lepiej wygląda Strategy II lun Strategy 2 lub Strategy B (najlepiej)
- w raporcie użytych jest 5 różnych krojów pisma (nie licząc strony tytułowej), za dużo
- strony nie są numerowane
- bardzo wąskie marginesy źle wyglądają, może warto zmniejszyć krój pisma o pół punktu ale zwiększyć trochę marginesy

**Comment by pbiecek** [comment]
Powinny być 4 strony a nie 5. Na okładce niepotrzebne są niebieskie obramówki, znacznie lepiej wyglądałyby białe kontury dla krajów i wyraźniejsze rozróżnienie wybranych krajów (teraz trudno zauważyć Koreę). Poza tym mając mapę spodziewałem się że będzie ona już pokazywała wyniki a nie tylko państwa wybrane do analizy. Link do źródeł (na końcu) powinien być adresem URL, pozostałby na wydruku a tak to nie wiadmo co kliknąć (jak ma się wydruk).
Początkowo zakładałem że rozdział ,,What if'' będzie inaczej wyglądał, ale jestem raczej pozytywnie zaskoczony.
Zadanie zaliczone, przesyłam ten raport do osoby z OECD i prześlę więcej uwag gdy dostanę jej odpowiedź.
